_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  advagg: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  blog: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_split: 0
  contact: 0
  contextual: 0
  csp: 0
  csp_extras: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entityqueue: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_captcha: 0
  image_styles_builder: 0
  imce: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  layout_builder: 0
  layout_discovery: 0
  libraries_ui: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  quick_node_clone: 0
  redirect: 0
  reroute_email: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  smtp: 0
  standard: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_image_select: 0
  webform_node: 0
  webform_options_custom: 0
  webform_options_limit: 0
  webform_scheduled_email: 0
  webform_schema: 0
  webform_share: 0
  webform_shortcuts: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  paragraphs: 11
theme:
  olivero: 0
  claro: 0
profile: standard
